name: Terminal Profile Update
on:
  push:
    paths:
      - 'data.json'
      - 'generate.py'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Compile Profile
        run: python generate.py
        
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: terminal profile updated" || exit 0
          git push
